### PR TITLE
build: propagation of GOPROXY env var

### PR DESCRIPTION
**Pull request by maitredede**
Hello,

For dev containers, expose the GOPROXY env for faster tests.

Signed-off-by: Damien DALY <maitredede@gmail.com>

## Checklist
- [&check;] Added tests for features and functional changes (N/A: build scripts)
- [&check;] Public functions and types are documented (N/A: no new functions/types)
- [&check;] Standard formatting is applied to Go code (N/A: no new go code)
- [&check;] Is this a new API? Added a new file that begins with `//go:build ceph_preview` (N/A: no new go code)
- [&check;] Ran `make api-update` to record new APIs (N/A: no new api)

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
Hi @maitredede this commit will need the signed off by line added to the commit just like from your other PR. I've also rebased it and am running the tests now.

**Comment by maitredede** [comment]
Hi @phlogistonjohn you are right, sorry for the miss. My next PR will be perfect :smile:

**Comment by phlogistonjohn** [comment]
> Hi @phlogistonjohn you are right, sorry for the miss. My next PR will be perfect smile

Perfection is not required. Collaboration is good enough for me!  :-D

**Review by phlogistonjohn — APPROVED** [review]
LGTM.

**Pull request merged**
