### PR TITLE
ci: remove "luminous" from testing matrix

### PR DESCRIPTION
**Pull request by phlogistonjohn**
We could probably have done this sooner, but now is better than later.

## Checklist
- [x] Added tests for features and functional changes
- [x] Public functions and types are documented
- [x] Standard formatting is applied to Go code

### CODE REVIEW

**Review by agarwal-mudit — APPROVED** [review]
lgtm

**Comment by agarwal-mudit** [comment]
CI is still waiting for the staus report for luminous

**Review by nixpanic — APPROVED** [review]
> CI is still waiting for the staus report for luminous

Yeah, not sure how to remove that part... It may be a configuration in the repository where I do not have permissions to check/modify.

**Comment by phlogistonjohn** [comment]
I think its a quirk of how ci integration works for the github ci.  I don't think its a major issue and I will just merge it anyway since I have two approvals.

**Pull request merged**
