### PR TITLE
devcontainer: simplify and remove Dockerfile

### PR DESCRIPTION
**Pull request by ansiwen**
This change simplifies the devcontainer setup by directly using the Dockerfile from the tests folder. It means, that all packages that are required by vscode (like linter and debugger and so on) will not be installed after the first fresh rebuild of the devcontainer. However, after vscode installed them once (with the button that pops up in the lower right corner), they will be stored in the cache volume (same as used by the tests with USE_CACHE), and after restarting or rebuilding the container, they will still be available.

Signed-off-by: Sven Anderson <sven@redhat.com>

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
Looks OK to me. As like last time it might be nice to have another vscode user take it for a spin before merging but it isn't required.

**Comment by ansiwen** [comment]
> Looks OK to me. As like last time it might be nice to have another vscode user take it for a spin before merging but it isn't required.

There's just @rajatsing, so he can try it out until tomorrow I would say. Otherwise I will just merge it.

**Comment by rajatsing** [comment]
I'll take a look at it

**Comment by rajatsing** [comment]
So I tested it but I am not sure what am I suppose to test here?. Is it for the caching of the downloads somewhere locally in the machine or something else that I might have missed?.
IF it was the caching f the downloaded packages, the no, it just downloads all the needed packages every time I run the test, the command that I am using to run the test is, here I was running the `TestGetMirrorUUID` test. 

```
make test-multi-container ENTRYPOINT_ARGS="--test-pkg rbd --test-run ^TestGetMirrorUUID$"
```
The output snippet below will be common for all the test, after downloading all these files, the actual test is executed
```
go: downloading golang.org/x/sys v0.0.0-20200501145240-bc7a7d42d5c3
go: downloading github.com/aws/aws-sdk-go v1.35.24
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/stretchr/testify v1.4.0
go: downloading github.com/gofrs/uuid v3.2.0+incompatible
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.0
go: downloading gopkg.in/yaml.v2 v2.2.8
github.com/ceph/go-ceph
github.com/ceph/go-ceph/internal/retry
golang.org/x/sys/internal/unsafeheader
github.com/ceph/go-ceph/rgw
github.com/ceph/go-ceph/common/commands
github.com/aws/aws-sdk-go/aws/client/metadata
github.com/ceph/go-ceph/internal/errutil
github.com/ceph/go-ceph/internal/cutil
golang.org/x/sys/unix
.
.
.
.
.
.
```

**Comment by ansiwen** [comment]
@rajatsing 
> So I tested it but I am not sure what am I suppose to test here?. Is it for the caching of the downloads somewhere locally in the machine or something else that I might have missed?.

Sorry, I probably should have given more context. See updated description.

> IF it was the caching f the downloaded packages, the no, it just downloads all the needed packages every time I run the test, the command below is what I am using to run the test, here I was running the `TestGetMirrorUUID` unit test.

No, it's not about the caching of the packages required for the tests. This you have to enable with USE_CACHE=1 like described in #513.

**Comment by ansiwen** [comment]
@mergifyio rebase

**Comment by ansiwen** [comment]
I merged this, because it was bothering me not having it in the master branch. If there are any issues coming up for you @rajatsing, I will fix short term. But I think at the moment I'm the only one actively using this.

**Comment by rajatsing** [comment]
My bad @ansiwen and yes to worked!.
I forgot to mention it in here.

**Pull request merged**
