### PR TITLE
Enable golint in travis and Makefile

### LINKED ISSUE #77: add golint to travis ci checks

### PR DESCRIPTION
**Pull request by MalloZup**
fix #77

### CODE REVIEW

**Comment by MalloZup** [comment]
@noahdesu  you can merge this. This is just an enablement. golint issues need to be fixed later

**Comment by noahdesu** [comment]
@MalloZup thanks. just curious, what exactly is this PR doing if it isn't fixing the linting problems? Is it disabling the lint for the files that need to eventually be fixed?

**Comment by MalloZup** [comment]
@noahdesu  yop no pb. Actually the super-beautiful pr would be to fix `golint` and then make it failing on CI.

However it will take much time to do it, and i don't have it currently.

This pr is just  enabling the make target `check` where one could have the whole errors and fixing them step by step. ( additionally make check target could be extended in future with `go fmt` checks etc)

Is just a small pr in that direction, doing `golint` fix would take more time

**Comment by noahdesu** [comment]
coo coo thanks for the explanation!

**Pull request merged**
