### PR TITLE
Add api : GetOmapValuesByKeys

### PR DESCRIPTION
**Pull request by chenji-kael**
Signed-off-by: chen ji <chen.ji@haihangyun.com>

### CODE REVIEW

**Comment by noahdesu** [comment]
Hi @chenji-kael , thanks! Would you mind adding a test case to test_rados.go ?

**Comment by noahdesu** [comment]
If anyone wants this change, I can fix it up. Otherwise I'm going to close it.

**Comment by runsisi** [comment]
@noahdesu i think it's useful, please keep it, thanks :)

**Comment by immesys** [comment]
This function would be useful to me

**Comment by phlogistonjohn** [comment]
@chenji-kael  Hi, thank you for your contributions to this project. This project had gone stale for a while and some of us are new contributors trying to update it and actively contribute. However, because we are not always familiar with the context of changes that were started a while ago before we were involved I'd like to ask you to update this PR with your current status and if you feel you would still like us to review it anew. If we do not hear from you in a few weeks we will probably close the PR as stale in order to lower our backlog. Thanks again!

**Comment by immesys** [comment]
If the original author doesn't respond after a while, please mention me and I am happy to take over in polishing/rebasing the PR.

**Comment by phlogistonjohn** [comment]
Thank you @immesys we will keep that in mind if there's no further response from the author.

**Comment by phlogistonjohn** [comment]
Closing PR after no author response.
@immesys please file free to file a *new* PR or issue around this topic to track your desire for it. If you file an issue but not a PR we'll get around to it when we can.

**Pull request closed without merging**
