### PR TITLE
contrib/apiage: Provide links to go docs for APIs

### LINKED ISSUE #592: apiage: add links to documentation
I had meant to add hyperlinks to the "official" go docs for go ceph when our tool generates the markdown table of deprecated and preview APIs. But I never got around to it. It should be straightforward use of the pkg name and `[<type>.]>func>` after the anchor (`#`)`.

### PR DESCRIPTION
**Pull request by anoopcs9**
fixes #592

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Did you try any of the links generated? I ask because I was under the impression that preview APIs would not show up on pkg.go.dev because there's no way to indicate to pkg.go.dev what build tags you want it to use. Therefore, it would not include anything that requires the ceph_preview build tag (see #601 ).

**Comment by ansiwen** [comment]
> I ask because I was under the impression that preview APIs would not show up on pkg.go.dev because there's no way to indicate to pkg.go.dev what build tags you want it to use.

That's not just your impression but a fact, easily confirmed by for example searching in the [rados docs](https://pkg.go.dev/github.com/ceph/go-ceph/rados) for `SetLocator`, which is in preview since v0.15.0.

This makes #592 a bit moot tbh, since then there will be just a few links to deprecated functions, that we don't want that people use anyway.

**Comment by anoopcs9** [comment]
> > I ask because I was under the impression that preview APIs would not show up on pkg.go.dev because there's no way to indicate to pkg.go.dev what build tags you want it to use.
> 
> That's not just your impression but a fact, easily confirmed by for example searching in the [rados docs](https://pkg.go.dev/github.com/ceph/go-ceph/rados) for `SetLocator`, which is in preview since v0.15.0.

Correct. I should have asked first the very same question when I noticed this issue with doc generation while making the change.

> This makes #592 a bit moot tbh, since then there will be just a few links to deprecated functions, that we don't want that people use anyway.

I agree.

**Comment by anoopcs9** [comment]
Following the discussion on #592 , I am taking the PR out.

**Pull request closed without merging**
