### PR TITLE
cutil: fix race condition in ptrguard tests

### PR DESCRIPTION
**Pull request by ansiwen**
The finalizer of an object is called in a separate go routine, so we
might have to check several times for its completion.

Fixes: #545

Signed-off-by: Sven Anderson <sven@redhat.com>

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
LGTM. It might be nice to add a comment mirroring what you have in the commit message so that people reading the code don't think the repeat calls to runtime.GC() are mistakes, but its minor.

**Comment by ansiwen** [comment]
Actually that doesn't really fix the race condition, because the finalizer is called in a separate go routine. I will push a different solution.

**Review by phlogistonjohn — APPROVED** [review]
LGTM

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Pull request merged**
