### PR TITLE
Enable a daily run of the CI

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Recently, changes to ceph nautilus reminded me that due to the low rate of PRs we don't always catch things that change in our dependencies right away. I propose adding a daily CI run that help catch these kind of things sooner and can help distinguish between a PR related failure and random flakiness and upstream changes.

Please do not merge until we are passing the CI runs again. I am filing this now because I wanted to (a) try out the syntax help in the built in github web editor and (b) do this before I forgot.

### CODE REVIEW

**Review by ansiwen — DISMISSED** [review]

**Comment by ansiwen** [comment]
LGTM

**Review by nixpanic — COMMENTED** [review]
Looks good, (unfortunately `@daily` is not supported according to the docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule).

You will want to update the commit message with some linebreaks, I guess?

**Comment by phlogistonjohn** [comment]
> Looks good, (unfortunately `@daily` is not supported according to the docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule).
> 

Indeed it is not. It's too bad but the web-based editor in github actually can process the line and show you when it will run in a tooltip.

> You will want to update the commit message with some linebreaks, I guess?

A negative side-effect of using the github editor. That and this branch isn't in my fork but in the "canonical" project repo. :-(

I won't fix it now, but it certainly discourages me from making a PR directly from the github ui in the future.  If that's ok I'll merge or if hear no objectionss early next week.

**Review by nixpanic — DISMISSED** [review]

**Comment by nixpanic** [comment]
@mergifyio refresh

**Comment by phlogistonjohn** [comment]
Silly bot, your laggy dismissal of the reviews are no match for my repo super powers!

**Pull request merged**
