### PR TITLE
repo: update new repo path

### PR DESCRIPTION
**Pull request by noahdesu**
noahdesu -> ceph

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>

### CODE REVIEW

**Comment by leseb** [comment]
Thanks @noahdesu!

**Comment by noahdesu** [comment]
@leseb assuming we want to keep using travis-ci, can you arrange to have go-ceph enabled in the travis-ci ceph account? I don't know who has those permissions...

**Comment by leseb** [comment]
@noahdesu hum I think you can use your own account for that, let me know that works. Do you see the repo when you log in travis?

**Comment by noahdesu** [comment]
@leseb Ok i'll poke around on that this evening and let you know if it doesn't work. It might be the case that it's better to just add some qa workunits so it can be part of the version matrix.

**Pull request merged**
