### PR TITLE
rbd: add SetMirrorSiteName and GetMirrorSiteName functions

### LINKED ISSUE #487: Missing rbd API components: mirror site name
The rbd API implements function(s) below but go-ceph does not:
* rbd_mirror_site_name_get
* rbd_mirror_site_name_set

This issue has been filed to track implementing this missing
functionality in the appropriate package within go-ceph.
Please refer to the Ceph C API for details about the function(s)
in question.

NOTE: This issue was generated by a script.
If the content looks wrong or the wording seems a bit odd
please excuse the script and blame @phlogistonjohn

### PR DESCRIPTION
**Pull request by phlogistonjohn**
* Add SetMirrorSiteName implementing rbd_mirror_site_name_set
* Add GetMirrorSiteName implementing rbd_mirror_site_name_get

These functions are used to set the name of the site (for an entire
cluster) for rbd mirroring purposes. It's a bit strange that it's
part of rbd and not rados, but such is life.

Tests included.

Fixes #487 

## Checklist
- [x] Added tests for features and functional changes
- [x] Public functions and types are documented
- [x] Standard formatting is applied to Go code

### CODE REVIEW

**Review by ansiwen — APPROVED** [review]
LGTM

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Review by ansiwen — APPROVED** [review]

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
@agarwal-mudit  @nixpanic  Please take a look. If no 2nd review by May 31 I think I will merge with only 1 review.

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Review by nixpanic — APPROVED** [review]

**Pull request merged**
