### PR TITLE
cephfs: implement MountInfo.SelectFilesystem

### LINKED ISSUE #818: mount non-default mds_namespace/volume by name
with [cephfs.CreateFromRados](https://pkg.go.dev/github.com/ceph/go-ceph@v0.19.0/cephfs#CreateFromRados) i get a MountInfo for the default volume, (i think). 

how do i use a different volume?

i think the C api might be `ceph_select_filesystem` ?

### PR DESCRIPTION
**Pull request by aep**
fixes #818

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Hi there! Thank you very much for the contribution.

One very important part of our contribution process is to add tests to the test suite for new API functions. This ensures that they do what they claim to do and prevents regressions across time and different versions of ceph.  In the PR checklist we have in the PR template there's an item that requests such tests.

One of the challenges of this particular API, and possibly one of the reasons it hasn't been added yet is that this will probably need changes to the small ceph container that our tests execute against. We'll need to add a 2nd file system (and a second mds IIRC) and then we'll be able to write Go tests that make use of the 2nd fs.

I'd be happy to guide and assist you with this process.  In addition to the test requirement there are few other process related items we ask with contributions: see the [pull request template](https://github.com/ceph/go-ceph/blob/master/.github/pull_request_template.md) for a brief checklist, and the [development guide doc](https://github.com/ceph/go-ceph/blob/master/docs/development.md) for more information.  If you have any questions or concerns feel free to ask!

**Comment by phlogistonjohn** [comment]
Hi there, I hope our requests don't seem to burdensome and you'll be able to work with us to add the tests.  However, if you simply don't have the time to work on this any more please let us know. We'll ask for your permission to use your patch as a starting point that we can base a different PR on. Thanks!

**Comment by aep** [comment]
sorry, i dont think i can fix the test environment.

it's a trivial change, so i dont think you need my permission, but of course you have it :)

**Comment by phlogistonjohn** [comment]
Thank you. Since I know there's interest in this feature I will try to work on it myself over the next few weeks. For now you can carry your change in a fork.  Thank you!

**Pull request closed without merging**
