### PR TITLE
rgw/admin: Add missing uid member to usage struct

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
## Description
Added the uid member to the usage type.
We don't need to handle the uid here, as the ceph function handles it in the backend.

Fixes: #758

Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

## Checklist
- [ ] Added tests for features and functional changes
- [ ] Public functions and types are documented
- [X] Standard formatting is applied to Go code
- [ ] Is this a new API? Added a new file that begins with `//go:build ceph_preview`
- [ ] Ran `make api-update` to record new APIs

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@thotz can you PTAL?
TIA :)

**Review by thotz — APPROVED** [review]

**Review by anoopcs9 — APPROVED** [review]
lgtm.

**Comment by anoopcs9** [comment]
@Mergifyio rebase

**Comment by anoopcs9** [comment]
> > rebase
> 
> #### x Unable to rebase: user `anoopcs9` is unknown.

Ok. I'll try once again.

**Comment by anoopcs9** [comment]
@Mergifyio rebase

**Comment by anoopcs9** [comment]
> > rebase
> 
> #### x Unable to rebase: user `anoopcs9` is unknown.
> 
> Please make sure `anoopcs9` has logged in Mergify dashboard.

Authorized..let's see now.

**Comment by anoopcs9** [comment]
@Mergifyio rebase

**Pull request merged**
