### PR TITLE
tests: add benchmarks for PtrGuard related types

### PR DESCRIPTION
**Pull request by ansiwen**
Signed-off-by: Sven Anderson <sven@redhat.com>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
On first blush it looks OK to me. But I want to get a proper run of it first before I do a full review pass.

**Review by phlogistonjohn — APPROVED** [review]
LGTM, thanks!

**Comment by phlogistonjohn** [comment]
@nixpanic  PTAL if you have a moment.

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Comment by ansiwen** [comment]
@Mergifyio rebase

**Review by nixpanic — APPROVED** [review]

**Pull request merged**
