### PR TITLE
add support for bucket quota

### PR DESCRIPTION
**Pull request by R4scal**
Resolve https://github.com/ceph/go-ceph/issues/931

### CODE REVIEW

**Review by thotz — COMMENTED** [review]
Need to define different api like this https://github.com/ceph/go-ceph/blob/master/rgw/admin/bucket_quota.go. Not modify existing ones. Define api like GetUserBucketQuota and SetUserBucketQuota IMO

**Comment by anoopcs9** [comment]
> But why make a separate function if it will make a request to the same rgw api method? The request will differ only in the data inside that the function takes as an argument... You will get two methods that do the same thing

Even though it differs only in the `quota-type` argument, _GetUserQuota()_ and _SetUserQuota()_ were specifically created to literally indicate the `quota-type` in API name itself. Therefore I suggest we add _GetBucketQuota()_ and _SetBucketQuota()_ separately within _rgw/admin/bucket_quota.go_ and corresponding tests within _rgw/admin/bucket_quota_test.go_.

**Comment by R4scal** [comment]
Hello. Done, added GetBucketQuota() and SetBucketQuota()

**Comment by R4scal** [comment]
I think I need to add new methods to `docs/api-status.json`. Should they be reflected somewhere else?

**Comment by phlogistonjohn** [comment]
> I think I need to add new methods to `docs/api-status.json`. Should they be reflected somewhere else?

Contributors can make api-update to record new APIs. It's noted in the pull request template and in the [dev doc](https://github.com/ceph/go-ceph/blob/master/docs/development.md#api-status). This command should automatically update the JSON and human-readable markdown file.

But in order for that to work correctly you need to put your new APIs into a separate file and add the ceph_preview build tag. Again, please refer to the linked doc.

**Comment by anoopcs9** [comment]
> I think I need to add new methods to `docs/api-status.json`. Should they be reflected somewhere else?

Sorry, I forgot to indicate the need for adding new APIs and corresponding tests into separate files as mentioned by @phlogistonjohn in the above comment. Therefore our next step would be to create(and add) new APIs and test in separate files like _user_bucket_quota.go_ and _user_bucket_quota_test.go_. This will help us in completing the CI runs by successfully running `Check API Versions and Aging` check.

I would also suggest to squash your intermediate changes like `fix fmt`, `move bucket quota to diffferent methods` into main commit to maintain better git history.

**Pull request closed without merging**
