### PR TITLE
Make preview APIs stable for v0.19

### LINKED ISSUE #793: APIs pending stability updates in v0.19.0
## Preview APIs due to become stable
* rados: IOContext.SetAllocationHint
* rados: WriteOp.SetAllocationHint
* rados: IOContext.Alignment
* rados: IOContext.RequiresAlignment
* rgw/admin: API.ListUsersBuckets
* rgw/admin: API.ListUsersBucketsWithStat
* rgw/admin: API.CreateKey
* rgw/admin: API.RemoveKey
* rgw/admin: API.SetIndividualBucketQuota

## Deprecated APIs due to be removed
n/a

> NOTE: This issue was automatically filed by a script.

### PR DESCRIPTION
**Pull request by anoopcs9**
Two packages had APIs becoming stable for release v0.19, scheduled for 13th December 2022.

Fixes #793

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Minor, but typo in `rados: Make IOContext.RequiresAlignemnt stable` - Alignment is spelled wrong

**Comment by anoopcs9** [comment]
> Minor, but typo in `rados: Make IOContext.RequiresAlignemnt stable` - Alignment is spelled wrong

Fixed and updated.

**Review by phlogistonjohn — APPROVED** [review]
LGTM

**Comment by phlogistonjohn** [comment]
@ansiwen @thotz  change looks good to me, but I'll wait about 24hrs in case either of you have feedback. Please review and add the no-API label, otherwise I'll just add the label tomorrow.

**Review by thotz — APPROVED** [review]
RGW changes LGTM

**Comment by phlogistonjohn** [comment]
> RGW changes LGTM

Thanks for looking!

**Pull request merged**
