### PR TITLE
rbd: Add mirror peer site API components

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
**Description:**
Added some API components of mirror peer site

Fixes: #486

## Checklist
- [X] Added tests for features and functional changes
- [x] Public functions and types are documented
- [X] Standard formatting is applied to Go code
- [x] Is this a new API? Added a new file that begins with `//go:build ceph_preview`
- [X] Ran `make api-update` to record new APIs

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
> Thanks for your contribution.
> 
> As a general note, go-ceph still expects new APIs and corresponding tests in separate source files(for example, _mirror_peer_site.go_ and _mirror_peer_site_test.go_]. This is done to ensure that we keep track of such new APIs in preview state for 2 releases(by default) before promoting to stable state. In addition it will help us to mention those APIs in [api-status.md](https://github.com/ceph/go-ceph/blob/master/docs/api-status.md). You may go through [API Status](https://github.com/ceph/go-ceph/blob/master/docs/development.md#api-status) section from [Developer's Guide](https://github.com/ceph/go-ceph/blob/master/docs/development.md) and [API Stability](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md) doc for more details.

I was about to confirm this part, thanks for the note. Will update the code accordingly.

**Comment by Nikhil-Ladha** [comment]
@anoopcs9 PTAL now, and could you please also retrigger the `quincy` test suite?

**Comment by phlogistonjohn** [comment]
Wow, very impressive contribution thanks!  Docs look OK so I can suggest you tick off that item in the checklist.  We hit two ci "flakes" but (I hope) we just got unlucky. I'll do a proper full review once we have the CI passing!

**Comment by Nikhil-Ladha** [comment]
> Wow, very impressive contribution thanks! Docs look OK so I can suggest you tick off that item in the checklist. We hit two ci "flakes" but (I hope) we just got unlucky. I'll do a proper full review once we have the CI passing!

Seems like it was _actually_ flaky 😅

**Comment by phlogistonjohn** [comment]
> Seems like it was _actually_ flaky sweat_smile

Indeed. There's a common-ish flake in go-ceph where the test suite runs and reports "FAIL" at the end but if you look back through the output there's no indication of a particular failed test.  I have yet to find out a cause and I have only ever seen it happen on the github ci, never when running tests locally.

**Comment by Nikhil-Ladha** [comment]
If everything looks fine, are we good to merge the PR?

**Review by anoopcs9 — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
