### PR TITLE
RGW/admin: add tenant to bucket struct field

### PR DESCRIPTION
**Pull request by krafZLorG**
RGW/admin: add tenant to bucket struct field

This change adds a new bucket struct field, so we can use rgw.admin.API.GetBucketInfo() to get a bucket's tenant.

```
$ radosgw-admin bucket stats --bucket "tenant0/qb001"
{
    "bucket": "qb001",
    "num_shards": 11,
    "tenant": "tenant0",
```

Signed-off-by: Dmitry Kvashnin <dm.kvashnin@gmail.com>

### CODE REVIEW

**Comment by anoopcs9** [comment]
Currently we don't verify the returned `Bucket` struct field in corresponding tests? At least in this context shouldn't we add a check to verify newly added `Tenant` field?

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
@krafZLorG @anoopcs9 @thotz  I'm not clear what the state of this PR is. Do we need changes, reviews, or some other form of attention?  I just triggered a rebase but I don't know where to go next with this.

**Comment by krafZLorG** [comment]
There is currently no test for checking the Bucket structure. Why is it a stop factor for adding a missing field? (https://github.com/ceph/go-ceph/pull/704)

**Review by anoopcs9 — COMMENTED** [review]
> There is currently no test for checking the Bucket structure. Why is it a stop factor for adding a missing field? (https://github.com/ceph/go-ceph/pull/704)

Alright. I tend to agree. I'll wait for others to have a say before final approval.

**Comment by phlogistonjohn** [comment]
Changes look OK to me but I'd prefer a 2nd review from a subject matter expert on RGW like @thotz - I don't think we need to require a new test although it would be nice, it could help avoid future regressions.

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Review by anoopcs9 — APPROVED** [review]

**Review by thotz — APPROVED** [review]

**Comment by phlogistonjohn** [comment]
:+1: :+1: thanks everyone, for both the contribution and reviews!

**Pull request merged**
