### PR TITLE
rados: simplify code and remove style warnings

### PR DESCRIPTION
**Pull request by ansiwen**
While reviewing #315 I found some code that could be simplified. While touching the file I also removed style warnings about variables with underscores. (Sorry, that should better go in separate commits, but it was too late.) 

Signed-off-by: Sven Anderson <sven@redhat.com>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
I hope you don't mind but I'd like to wait a little on this to see if we can land PR #315 before the v0.7 release. If #315 does not appear likely to make it in, then we can consider this to make an incremental improvement.

**Comment by ansiwen** [comment]
Sure, no worries. I don't care in which order me merge that. Just wanted to push it quickly so I don't forget.

**Comment by phlogistonjohn** [comment]
I tried to incorporate the style cleanups into #408. While normally I would be happy to take this in before doing work the stuff that became 408 has been in flight for so long I'd prefer we just push towards that. Taking this now would just make me deal with a bunch of conflicts at rebase time. I hope you understand.

**Comment by phlogistonjohn** [comment]
@ansiwen this needs a rebase (or is possibly redundant now). Can you please take a look, thanks?

**Comment by ansiwen** [comment]
Yes, redundant. Closing.

**Pull request closed without merging**
