### PR TITLE
cephfs : add missing cephfs API components: fuction ceph_version

### PR DESCRIPTION
**Pull request by oct28-yjkim**
cephfs: add missing cephfs API Components: function ceph_version 

Signed-off-by: yjkim <oct28.yjkim@gmail.com]>

## Checklist
- [O] Added tests for features and functional changes
- [O] Public functions and types are documented
- [O] Standard formatting is applied to Go code

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
Thank you for the contribution! The code looks ok to me.

**Review by phlogistonjohn — CHANGES_REQUESTED** [review]
Sorry I missed a couple things when I approved a moment ago, the code still looks OK but the commits need some fixing:
* The two commits should be squashed together
* There's a spelling mistake in the commit message "fuction" should be "function"
* You should add a "Signed-off-by:" to the commit (see: https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for )

We don't strictly require the latter today, but its still a good thing to do. If you are not clear on how to accomplish the above, please just ask and we'll try to walk you through the git commands you need to use.

**Review by phlogistonjohn — CHANGES_REQUESTED** [review]
Thank you for squashing the changes, adding the Signed-off-by, and fixing the typo. Unfortunately, there's a new issue with the commit message. It now reads: "265 add missing cephfs API components: function ceph_version "

I'm not sure what the "256" is, maybe just a copy-n-paste error, but generally we want commit messages in go-ceph to follow the "<topic>: <description>" formula, where in this case topic is "cephfs". So could you please change it to something like: "cephfs: add missing API components: function ceph_version "

Thanks!

**Comment by oct28-yjkim** [comment]
265 is project isseue number. that was my fault. 
i fixed commit msg. 
please review this PR.

**Comment by phlogistonjohn** [comment]
> 265 is project isseue number. that was my fault.
> i fixed commit msg.
> please review this PR.

Understood.  Unfortunately, the commit message appears unchanged at the moment.

**Review by phlogistonjohn — APPROVED** [review]
LGTM now, thanks for making those changes, I really appreciate it.

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
@ansiwen I just rebased this PR. When it's done could you please take a look when you have a moment? thank you

**Comment by ansiwen** [comment]
Unfortunately CI is failing.

**Review by ansiwen — APPROVED** [review]
LGTM

**Review by ansiwen — APPROVED** [review]

**Comment by ansiwen** [comment]
Actually, our new [API policy](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md) would require this to be tagged as "preview". But it is so simple, that I have no issue merging it as stable. Also I'm not 100% sure, when we will start to enforce the new policy.

**Comment by ansiwen** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
> Actually, our new [API policy](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md) would require this to be tagged as "preview". But it is so simple, that I have no issue merging it as stable. Also I'm not 100% sure, when we will start to enforce the new policy.

Yeah, sorry for not thinking about that, but as you say this api was very simple and it was basically a copy of what rbd/rados already did.

**Pull request merged**
