### PR TITLE
rbd: Remove invalid snap ID test skip

### LINKED ISSUE #440: rbd: remove test skips for non-existing snap ID issue (test audit)
Ceph issue: https://tracker.ceph.com/issues/47287

Tests that call the function  rbd_snap_get_timestamp with a non-existing snapshot id are currently skipped due to the above ceph issue. Once all supported ceph versions contain fixes this skip can be removed.

Originally part of #207

### PR DESCRIPTION
**Pull request by anoopcs9**
Fix for https://tracker.ceph.com/issues/47287 is now available with quincy and above releases. Therefore do not skip `GetSnapTimestamp` API test for an invalid snap ID.

fixes #440 

depends on ceph [v17.2.8](https://github.com/ceph/ceph/milestone/18) GA.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
One example failure, FWIW:
```
# github.com/ceph/go-ceph/rbd [github.com/ceph/go-ceph/rbd.test]
rbd/snapshot_test.go:21:18: undefined: os
rbd/snapshot_test.go:23:3: undefined: serverVersion
rbd/snapshot_test.go:158:10: undefined: serverVersion
```

**Comment by anoopcs9** [comment]
Quincy backport is pending a release and thus CI job failed with SIGABRT for **_test-suite (quincy)_**. I can see that https://github.com/ceph/ceph/pull/55473 is already merged for [v17.2.8](https://github.com/ceph/ceph/milestone/18) milestone.

**Review by phlogistonjohn — APPROVED** [review]
lgtm

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
@Mergifyio rebase

**Comment by phlogistonjohn** [comment]
@Mergifyio rebase

**Comment by anoopcs9** [comment]
phew..finally 😓 .

**Pull request merged**
