### PR TITLE
rbd: metadata "list" function

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Light refactoring of the locations of some of the prior image metadata functions.

Add ListMetadata implementing rbd_metadata_list. The names a bit wonky (see commit msg) but I think its fine. Let me know if you think its confusing and we can discuss alternatives.

Fixes: #384 

## Checklist
- [x] Added tests for features and functional changes
- [x] Public functions and types are documented
- [x] Standard formatting is applied to Go code

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
It appears that this weeks release of ceph nautilus is now breaking the cephfs admin test suite. Please bear with me as I investigate these failures.

**Review by nixpanic — APPROVED** [review]

**Comment by phlogistonjohn** [comment]
@Mergifyio rebase

**Review by agarwal-mudit — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio refresh

**Comment by phlogistonjohn** [comment]
@Mergifyio rebase

**Pull request merged**
