### PR TITLE
rbd: export image name

### PR DESCRIPTION
**Pull request by clwluvw**
Signed-off-by: Seena Fallah <seenafallah@gmail.com>

## Checklist
- [x] Added tests for features and functional changes
- [x] Public functions and types are documented
- [x] Standard formatting is applied to Go code

### CODE REVIEW

**Comment by nixpanic** [comment]
Thanks for the PR!

Could you explain why you need this detail to be public? I would be more comfortable to add a `Image.GetName()` function, which prevents changing the `Image.name` of the object and getting things out of sync. Is that an alternative that works for you too?

**Comment by clwluvw** [comment]
> Thanks for the PR!
> 
> Could you explain why you need this detail to be public? I would be more comfortable to add a `Image.GetName()` function, which prevents changing the `Image.name` of the object and getting things out of sync. Is that an alternative that works for you too?

@nixpanic I need it for the programming use case. For example, when I pass an `rbd.Image` to a function I need its name and because the name is not exported I can't get it from the image object.
Yes, it's ok to me. I changed to the PR to return name with`GetName` func.

**Review by nixpanic — APPROVED** [review]
Looks good to me. This adds a new API, but it is so simple that I do not think it needs the `ceph_preview` build-constraint.

**Comment by clwluvw** [comment]
@nixpanic Seems the failures are not related to my changes 🤔

**Comment by phlogistonjohn** [comment]
@ansiwen do you have any objections to making exceptions to the API stability policy for extremely simple and straightforward changes like this one? I am. However, before I approve and merge I want to give you a chance to reply. Thanks!

**Comment by nixpanic** [comment]
> @nixpanic Seems the failures are not related to my changes thinking

No problem, this is a known issue and being addressed by #607

**Comment by phlogistonjohn** [comment]
FWIW the go-ceph project uses mergify, so manually force pushing can invalidate existing reviews.
You can request a rebase from mergify by creating a comment like:
```
@Mergifyio rebase
```

**Review by nixpanic — APPROVED** [review]

**Comment by ansiwen** [comment]
> @ansiwen do you have any objections to making exceptions to the API stability policy for extremely simple and straightforward changes like this one? I am. However, before I approve and merge I want to give you a chance to reply. Thanks!

@phlogistonjohn no objections

**Review by ansiwen — APPROVED** [review]
LGTM, thanks!

**Comment by ansiwen** [comment]
@Mergifyio rebase

**Pull request merged**
