### PR TITLE
rbd: add DeepCopy()

### PR DESCRIPTION
**Pull request by nixpanic**
With rbd_deep_copy() an image can be copied with selected options. This
can be used to create a copy and flatten the image in one go.

Updates: ceph/ceph-csi#2077

## Checklist
- [x] Added tests for features and functional changes
- [x] Public functions and types are documented
- [x] Standard formatting is applied to Go code

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]
I kind of wish there was an obviously better home for the new function than rbd.go, as I already consider it too large... but that's not the case today. Otherwise, the API and tests generally LGTM. Thanks!

**Comment by phlogistonjohn** [comment]
The CI issue ought to resolve when ceph-container pushes a new container image matching yesterday's [ceph release](https://ceph.io/releases/v15-2-13-octopus-released/). We can restart the CI run then and it should stop hitting the rpm error.

**Comment by nixpanic** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Review by agarwal-mudit — APPROVED** [review]

**Pull request merged**
