### PR TITLE
cephfs: add subvolume snapshot metadata APIs

### PR DESCRIPTION
**Pull request by pkalever**
## Description
Exports below APIs:
SetSnapshotMetadata,
GetSnapshotMetadata(),
RemoveSnapshotMetadata(),
ForceRemoveSnapshotMetadata() and
ListSnapshotMetadata()

Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

## Checklist
- [x] Added tests for features and functional changes
- [x] Public functions and types are documented
- [x] Standard formatting is applied to Go code
- [x] Is this a new API? Is this new API marked PREVIEW?

Additional information to reviewers/Maintainers:
~~This PR needs https://github.com/ceph/ceph/pull/46086 which is not merged upstream yet, but the cmd schemas will mostly be same.~~
Update: https://github.com/ceph/ceph/pull/46086 is merged upstream now.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Comment by phlogistonjohn** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
@Mergifyio rebase

**Comment by pkalever** [comment]
@phlogistonjohn @ansiwen could you please help review.

**Comment by phlogistonjohn** [comment]
This has the same api-status.json issue as PR #691.  Also, I think the PRs conflict with each other, no?  Maybe we should just focus on #691 first?

**Comment by pkalever** [comment]
> This has the same api-status.json issue as PR #691. Also, I think the PRs conflict with each other, no? Maybe we should just focus on #691 first?

Yes @phlogistonjohn I will address the comments and rebase this resolving the conflicting parts post #691 merge.

**Review by ansiwen — APPROVED** [review]
LGTM. When my approval gets lost later after rebasing, feel free to merge it also without me re-approval.

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Pull request merged**
